[build]
  base = "server-update/"
  publish = "public/"
  command = "npm run build"
  functions = "functions"

[functions]
  directory = "functions/"
  node_bundler = "esbuild"
  included_files = ["releases/**"]

[[redirects]]
  from = "/api/updates/latest"
  to = "/.netlify/functions/updates/latest"
  status = 200

[[redirects]]
  from = "/api/updates/latest/:channel"
  to = "/.netlify/functions/updates/latest/:channel"
  status = 200

[[redirects]]
  from = "/api/updates/releases/:channel"
  to = "/.netlify/functions/updates/releases/:channel"
  status = 200

[[redirects]]
  from = "/api/updates/version/*"
  to = "/.netlify/functions/updates/version/:splat"
  status = 200

[[redirects]]
  from = "/api/admin/publish"
  to = "/.netlify/functions/updates/admin/publish"
  status = 200

[[redirects]]
  from = "/api/admin/upload"
  to = "/.netlify/functions/updates/admin/upload"
  status = 200

[dev]
  command = "npm run netlify:dev"
  port = 3005
  functions = "functions" 