[build]
  base = "server-update/"
  publish = "public/"
  command = "npm run build"
  functions = "functions"

[functions]
  directory = "functions/"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  command = "npm run dev"
  port = 3005
  functions = "functions" 